# Generated by Django 5.0 on 2023-12-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('designation', models.TextField()),
                ('access', models.TextField()),
                ('salary', models.PositiveIntegerField()),
                ('deduction', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.company')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_REGISTER',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(null=True)),
                ('Time_diff', models.TimeField(null=True)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
