# Generated by Django 4.2.6 on 2024-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
