# Generated by Django 4.2.6 on 2024-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_rename_designation_employee_role_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.TextField(),
        ),
    ]
